In [112]:
import os

import pandas as pd
import numpy as np

In [3]:
bids_dir = os.path.abspath('/bgfs/bchandrasekaran/krs228/data/SSP/data_bids/')

#### Load the `participants.tsv` file from the BIDS directory

In [21]:
tsv_fpath = os.path.join(bids_dir, 'participants.tsv')
tsv_pd = pd.read_csv(tsv_fpath, delimiter='\t')

In [23]:
tsv_pd.columns

Index(['participant_id', 'age', 'sex', 'group'], dtype='object')

In [26]:
tsv_pd.sort_values(by=['participant_id'], inplace=True)

In [27]:
tsv_pd.head()

   participant_id  age sex    group
0      sub-SSP001   11   F  control
4      sub-SSP002   13   F  control
6      sub-SSP005   10   F  control
27     sub-SSP008    9   M  control
17     sub-SSP009    9   M  control

In [31]:
# make a set of Subject IDs that appear in tsv_pd
keep_ids = (tsv_pd['participant_id'].str.replace('sub-', '', regex=False).unique() )
print(keep_ids[:5])

['SSP001' 'SSP002' 'SSP005' 'SSP008' 'SSP009']

#### Load the MRI subject log

In [7]:
mri_table_fpath = 'SSP_MRI_2026-01-07.xlsx'

mri_table = pd.read_excel(mri_table_fpath)

In [10]:
mri_table

,Subject,M/F,DOB,MRI Date,Age at MRI,CWS,Notes
0,SSP001,F,2012-08-22,2023-10-19,11.164384,N,NaN
1,SSP002,F,2010-10-26,2023-10-28,13.013699,N,NaN
2,SSP005,F,2013-04-01,2023-09-25,10.490411,N,NaN
3,SSP008,M,2015-11-16,2024-06-02,8.550685,N,NaN
4,SSP009,M,2014-02-17,2024-01-02,9.879452,N,NaN
...,...,...,...,...,...,...,...
57,SSP102,F,2017-01-13,2025-08-07,8.569863,S,only got through a few minutes
58,SSP103,M,2014-09-27,2025-09-22,10.994521,N,NaN
59,SSP105,M,2016-07-04,2025-10-20,9.301370,S,no badaga
60,SSP106,M,2016-07-04,2025-10-20,9.301370,S,only the first few tasks (before badaga/alice)
61,SSP107,M,2014-08-22,2025-12-07,11.301370,S,only alice (no badaga/mpm)

In [36]:
# filter mri_table
mri_table_filt = mri_table[mri_table['Subject'].isin(keep_ids)].reset_index(drop=True)

In [37]:
mri_table_filt

,Subject,M/F,DOB,MRI Date,Age at MRI,CWS,Notes
0,SSP001,F,2012-08-22,2023-10-19,11.164384,N,NaN
1,SSP002,F,2010-10-26,2023-10-28,13.013699,N,NaN
2,SSP005,F,2013-04-01,2023-09-25,10.490411,N,NaN
3,SSP008,M,2015-11-16,2024-06-02,8.550685,N,NaN
4,SSP009,M,2014-02-17,2024-01-02,9.879452,N,NaN
5,SSP011,M,2012-08-02,2024-01-28,11.495890,N,NaN
6,SSP012,M,2010-11-13,2023-11-06,12.989041,N,NaN
7,SSP013,M,2012-11-20,2023-11-28,11.027397,N,NaN
8,SSP014,F,2012-05-01,2023-11-08,11.528767,N,NaN
9,SSP015,M,2014-08-19,2024-04-25,9.690411,N,NaN
10,SSP017,M,2012-12-16,2024-03-03,11.219178,N,NaN
11,SSP018,F,2014-12-20,2023-12-07,8.969863,S,NaN
12,SSP020,F,2010-08-19,2023-11-11,13.238356,S,NaN
13,SSP021,M,2015-07-18,2023-11-27,8.367123,S,NaN
14,SSP028,M,2013-04-17,2024-02-08,10.819178,N,NaN
15,SSP032,M,2011-03-18,2024-02-27,12.956164,N,NaN
16,SSP033,F,2016-03-04,2023-12-08,7.767123,N,NaN
17,SSP034,F,2014-10-30,2024-02-07,9.279452,N,NaN
18,SSP036,M,2012-05-23,2024-01-04,11.624658,N,NaN
19,SSP038,M,2014-05-01,2024-04-01,9.926027,N,NaN
20,SSP039,M,2011-03-17,2024-02-20,12.939726,N,NaN
21,SSP040,F,2015-03-21,2024-03-27,9.024658,N,NaN
22,SSP041,M,2012-08-15,2024-03-10,11.575342,N,actually a CWS but didn't identify
23,SSP045,M,2013-06-18,2024-03-10,10.734247,S,NaN
24,SSP046,M,2015-06-26,2025-01-05,9.536986,S,NaN
25,SSP048,M,2015-07-10,2024-07-01,8.983562,S,NaN
26,SSP051,F,2016-01-09,2024-02-28,8.142466,N,NaN
27,SSP054,F,2012-11-20,2024-08-16,11.745205,N,NaN
28,SSP056,F,2017-02-23,2025-05-23,8.249315,N,good
29,SSP058,F,2017-04-18,2025-01-07,7.728767,S,fine
30,SSP060,M,2016-11-10,2025-01-21,8.202740,N,NaN
31,SSP062,M,2017-04-01,2025-04-28,8.079452,N,fine
32,SSP064,M,2012-10-31,2024-08-13,11.791781,S,NaN
33,SSP074,M,2015-01-02,2024-12-02,9.923288,N,good
34,SSP076,F,2013-09-30,2025-03-28,11.498630,N,good
35,SSP077,M,2016-07-27,2025-02-17,8.567123,N,DNF (stopped alice p1)
36,SSP078,M,2014-03-27,2025-02-16,10.901370,S,DNF (stopped alice p2)
37,SSP081,M,2017-07-18,2025-04-14,7.745205,S,1 round badagama
38,SSP083,F,2016-08-10,2025-03-30,8.641096,N,good
39,SSP084,M,2014-03-19,2025-05-30,11.205479,N,"scan paused during alice p2, continued after"
40,SSP085,F,2017-10-25,2025-05-13,7.553425,N,good
41,SSP086,F,2017-09-05,2025-05-25,7.723288,N,good
42,SSP089,M,2016-12-02,2025-08-11,8.695890,S,NaN
43,SSP090,M,2016-12-05,2025-04-21,8.380822,S,good
44,SSP091,M,2014-06-29,2025-07-10,11.038356,N,NaN
45,SSP092,F,2015-07-17,2025-06-03,9.887671,N,"lots of movement, no MPMs"
46,SSP093,M,2016-07-19,2025-08-04,9.049315,S,NaN
47,SSP094,M,2015-07-14,2025-05-16,9.846575,S,good
48,SSP095,F,2014-08-07,2025-09-19,11.126027,N,good
49,SSP097,F,2017-01-29,2025-07-21,8.479452,N,NaN
50,SSP099,F,2013-08-21,2025-08-19,12.002740,N,one of the mfc's ran at 4mm (wrong slice copied)
51,SSP100,M,2018-01-18,2025-09-23,7.684932,N,NaN
52,SSP102,F,2017-01-13,2025-08-07,8.569863,S,only got through a few minutes
53,SSP103,M,2014-09-27,2025-09-22,10.994521,N,NaN
54,SSP106,M,2016-07-04,2025-10-20,9.301370,S,only the first few tasks (before badaga/alice)
55,SSP107,M,2014-08-22,2025-12-07,11.301370,S,only alice (no badaga/mpm)

#### Load the assessment covariate table

In [9]:
cov_table_fpath = 'SSP_AUD_2026-01-09.xlsx'
cov_table = pd.read_excel(cov_table_fpath)

In [11]:
cov_table

,Subject ID,Group,Gender,Age,TONI_INDEX,CTOPP_PhonologicalAwareness,CELF_CoreLang,CELF_Receptive,CELF_ExpressiveLang,hz_r_500,...,hz_r_8000,hz_l_500,hz_l_1000,hz_l_2000,hz_l_4000,hz_l_6000,hz_l_8000,PTA,win_correct_average,win_score_average
0,SSP001,N,F,9;10,89,75,96.0,93.0,106.0,PASSED,...,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,NaN,NaN,NaN
1,SSP002,N,F,12;0,104,100,114.0,100.0,112.0,PASSED,...,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,NaN,NaN,NaN
2,SSP003,N,F,12;1,111,116,135.0,133.0,135.0,PASSED,...,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,NaN,NaN,NaN
3,SSP004,N,F,8;4,95,110,102.0,109.0,98.0,PASSED,...,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,NaN,NaN,NaN
4,SSP005,N,F,9;6,100,96,108.0,98.0,112.0,PASSED,...,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,SSP518,S,F,6;7,120,118,122.0,133.0,118.0,15,...,10,20,10,15,20,10,10,14.375,24.0,6.8
119,SSP519,N,M,NaN,120,110,123.0,129.0,118.0,15,...,15,30,30,25,15,5,5,16.875,24.5,6.4
120,SSP520,N,F,NaN,102,75,94.0,98.0,89.0,10,...,0,0,5,5,10,20,5,5.000,28.5,3.2
121,SSP521,S,M,12,93,80,96.0,102.0,91.0,10,...,5,10,5,10,15,5,15,8.750,27.5,4.0
122,SSP522,S,M,6;10,108,96,96.0,107.0,96.0,-5,...,10,10,10,5,0,20,15,5.000,23.0,7.6

In [51]:
# filter cov_table
cov_table_filt = cov_table[cov_table['Subject ID'].isin(keep_ids)].reset_index(drop=True)

#cov_table_filt.rename(columns={'Subject ID': 'participant_id'}, inplace=True)

In [52]:
cov_table_filt

,Subject ID,Group,Gender,Age,TONI_INDEX,CTOPP_PhonologicalAwareness,CELF_CoreLang,CELF_Receptive,CELF_ExpressiveLang,hz_r_500,...,hz_r_8000,hz_l_500,hz_l_1000,hz_l_2000,hz_l_4000,hz_l_6000,hz_l_8000,PTA,win_correct_average,win_score_average
0,SSP001,N,F,9;10,89,75,96.0,93.0,106.0,PASSED,...,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,NaN,NaN,NaN
1,SSP002,N,F,12;0,104,100,114.0,100.0,112.0,PASSED,...,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,NaN,NaN,NaN
2,SSP005,N,F,9;6,100,96,108.0,98.0,112.0,PASSED,...,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,NaN,NaN,NaN
3,SSP008,N,M,7;2,104,98,113.0,117.0,120.0,PASSED,...,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,PASSED,NaN,NaN,NaN
4,SSP009,N,M,8;9,101,98,111.0,89.0,116.0,10,...,0,10,5,0,0,0,0,NaN,NaN,NaN
5,SSP011,N,M,10;1,114,84,117.0,105.0,122.0,15,...,-5,10,10,10,0,-5,-5,NaN,NaN,NaN
6,SSP012,N,M,11;10,111,94,100.0,102.0,98.0,15,...,-10,10,0,0,0,-5,-5,NaN,NaN,NaN
7,SSP013,N,M,10;1,99,71,85.0,77.0,89.0,20,...,0,15,10,-5,0,-5,-10,NaN,NaN,NaN
8,SSP014,N,F,10;6,120,114,116.0,111.0,114.0,10,...,0,10,5,0,0,5,-10,NaN,NaN,NaN
9,SSP015,N,M,8;4,100,100,96.0,107.0,98.0,10,...,-10,5,5,10,5,0,-10,NaN,NaN,NaN
10,SSP017,N,M,9;9,115,96,117.0,113.0,118.0,10,...,0,15,10,5,-5,0,-10,NaN,NaN,NaN
11,SSP018,S,F,7;9,102,103,102.0,94.0,106.0,20,...,0,20,15,5,15,-5,-5,NaN,NaN,NaN
12,SSP020,S,F,12;2,98,110,133.0,122.0,135.0,10,...,-5,5,5,0,-5,0,0,NaN,NaN,NaN
13,SSP021,S,M,7;2,115,129,133.0,129.0,134.0,10,...,-5,10,5,10,5,5,0,NaN,NaN,NaN
14,SSP028,N,M,10;3,107,116,100.0,102.0,100.0,5,...,-5,10,-5,5,-5,-5,-5,NaN,26.5,4.8
15,SSP032,N,M,12;5,114,110,105.0,107.0,104.0,10,...,-5,10,10,10,0,5,15,NaN,27.0,4.4
16,SSP033,N,F,7;6,99,92,107.0,121.0,106.0,5,...,0,5,0,0,5,0,-5,NaN,25.5,5.6
17,SSP034,N,F,8;10,106,103,123.0,104.0,122.0,5,...,-5,5,0,5,5,-5,0,NaN,24.5,6.4
18,SSP036,N,M,11;5,128,114,140.0,135.0,133.0,10,...,-5,0,5,0,-5,-5,-5,0.625,25.5,5.6
19,SSP038,N,M,9;6,100,75,101.0,103.0,93.0,15,...,0,5,5,5,5,5,-5,7.500,25.0,6.0
20,SSP039,N,M,12;7,88,98,105.0,109.0,104.0,5,...,0,15,15,10,5,-5,0,7.500,27.0,4.4
21,SSP040,N,F,8;7,139,100,123.0,123.0,126.0,20,...,-5,20,15,10,5,0,-10,14.375,28.0,3.6
22,SSP041,N,M,11;3,125,90,107.0,113.0,104.0,5,...,-10,10,5,0,0,0,-5,3.125,25.5,5.6
23,SSP045,S,M,9;11,106,80,117.0,117.0,110.0,20,...,-10,5,5,0,0,5,5,5.625,27.0,4.4
24,SSP046,S,M,8;6,104,112,125.0,131.0,124.0,10,...,0,10,0,5,5,5,-5,5.000,26.0,5.2
25,SSP048,S,M,8;6,107,96,111.0,135.0,108.0,5,...,0,10,5,0,0,-5,-5,3.750,26.0,5.2
26,SSP051,N,F,8;1,106,84,118.0,115.0,116.0,15,...,5,10,15,5,5,10,10,9.375,27.0,4.4
27,SSP054,N,F,11;3,108,112,127.0,125.0,124.0,10,...,0,10,10,0,10,5,0,6.875,27.0,4.4
28,SSP056,N,F,7;1,105,114,120.0,111.0,116.0,20,...,20,20,15,10,5,-5,10,11.875,25.0,6.0
29,SSP058,S,F,7;0,110,90,95.0,85.0,98.0,15,...,0,15,10,10,10,10,0,11.250,24.5,6.4
30,SSP060,N,M,7;5,96,135,113.0,102.0,116.0,0,...,-5,0,10,5,0,-5,5,3.125,26.0,5.2
31,SSP062,N,M,7;1,80,82,111.0,89.0,118.0,15,...,0,15,10,5,5,0,0,9.375,24.5,6.4
32,SSP064,S,M,11;7,97,84,94.0,102.0,93.0,10,...,0,15,10,15,5,15,10,10.625,26.0,5.2
33,SSP074,N,M,9;8,99,105,120.0,120.0,116.0,10,...,0,5,5,-5,5,10,5,5.000,25.5,5.6
34,SSP076,N,F,11;0,97,84,113.0,113.0,106.0,10,...,0,5,10,-5,-5,20,10,1.875,25.5,5.6
35,SSP077,N,M,8;2,87,92,85.0,85.0,87.0,5,...,5,10,5,-10,-10,10,0,-0.625,23.0,7.6
36,SSP078,S,M,10;7,88,82,103.0,91.0,114.0,5,...,5,10,5,0,-5,10,10,3.125,25.0,6.0
37,SSP081,S,M,7;4,104,105,104.0,109.0,108.0,0,...,5,5,5,5,-10,10,0,1.250,23.0,7.6
38,SSP083,N,F,8;3,121,100,109.0,117.0,118.0,0,...,5,5,0,5,-10,0,-5,0.625,25.5,5.6
39,SSP084,N,M,10;8,111,100,100.0,93.0,106.0,5,...,0,5,0,0,0,10,0,1.250,25.0,6.0
40,SSP085,N,F,7;1,109,127,120.0,121.0,116.0,10,...,15,10,0,0,0,5,15,3.750,23.5,7.2
41,SSP086,N,F,7;4,100,103,107.0,107.0,112.0,15,...,15,10,10,5,10,15,15,7.500,24.5,6.4
42,SSP089,S,M,8;3,96,107,105.0,102.0,110.0,10,...,0,10,10,0,10,15,5,6.875,21.0,9.2
43,SSP090,S,M,8;3,106,112,109.0,100.0,114.0,30,...,15,5,-5,-5,-10,10,5,5.625,25.0,6.0
44,SSP091,N,M,10;9,104,98,113.0,105.0,108.0,0,...,5,0,5,5,0,0,10,1.250,25.5,5.6
45,SSP092,N,F,9;8,114,98,105.0,102.0,108.0,5,...,0,5,-10,-5,5,10,0,0.625,24.0,6.8
46,SSP093,S,M,8;8,100,88,98.0,92.0,100.0,10,...,10,10,0,-5,5,5,5,2.500,25.5,5.6
47,SSP094,S,M,9;9,100,94,96.0,86.0,110.0,15,...,15,5,10,10,15,30,10,10.625,26.0,5.2
48,SSP095,N,F,10;9,114,122,127.0,127.0,126.0,10,...,5,5,5,5,0,5,15,4.375,26.5,4.8
49,SSP097,N,M,7;3,98,110,98.0,94.0,106.0,10,...,15,10,0,5,10,20,5,5.625,24.0,6.8
50,SSP099,N,F,11;9,107,94,126.0,131.0,120.0,-5,...,-10,0,-10,-10,-10,-10,-5,-7.500,26.0,5.2
51,SSP100,N,M,7;4,105,122,111.0,109.0,114.0,10,...,10,10,5,-10,0,5,5,1.875,24.5,6.4
52,SSP102,S,F,8;5,96,96,85.0,85.0,89.0,10,...,-10,10,5,-5,0,10,-5,3.750,24.0,6.8
53,SSP103,N,M,10;9,103,98,102.0,103.0,106.0,10,...,-10,10,5,-5,0,10,-5,3.750,24.0,6.8

### Combine data into new participants_tsv table

In [93]:
mri_cols_to_add = ['Subject', 'Age at MRI']

In [125]:
cov_cols_to_add = [
    'Subject ID',
    'TONI_INDEX',
    'CTOPP_PhonologicalAwareness',
    'CELF_CoreLang',
    'CELF_Receptive',
    'CELF_ExpressiveLang',
    'PTA', 'win_correct_average', 'win_score_average' # not all participants
]

covar_rename = {
    'TONI_INDEX': 'toni_index',
    'CTOPP_PhonologicalAwareness': 'ctopp_phon_awareness',
    'CELF_CoreLang': 'celf_core_language',
    'CELF_Receptive': 'celf_receptive_language',
    'CELF_ExpressiveLang': 'celf_expressive_language',
    'PTA': 'pta',
    'win_correct_average': 'win_correct_avg',
    'win_score_average': 'win_score_avg'
}

In [126]:
# add Subject ID to tsv_pd
tsv_pd = tsv_pd.assign(
    Subject_ID=tsv_pd['participant_id'].str.replace('sub-', '', regex=False) )

# merge selected columns from mri_table_filt
new_tsv_pd = tsv_pd.merge(
    mri_table_filt[mri_cols_to_add],
    left_on='Subject_ID',
    right_on='Subject',
    how='left'
)

# merge selected columns from cov_table_filt
new_tsv_pd = new_tsv_pd.merge(
    cov_table_filt[cov_cols_to_add],
    left_on='Subject_ID',
    right_on='Subject ID',
    how='left'
)

# replace the redundant subject ID columns
new_tsv_pd.drop(columns=['Subject_ID'], inplace=True)
new_tsv_pd.drop(columns=['Subject ID'], inplace=True)
new_tsv_pd.drop(columns=['Subject'], inplace=True)

# drop original 'age' (which was an estimate)
new_tsv_pd.drop(columns=['age'], inplace=True)
new_tsv_pd.rename(columns={'Age at MRI': 'age'}, inplace=True)

# BIDS-friendly renaming
new_tsv_pd.rename(columns=covar_rename, inplace=True)
new_tsv_pd['group'] = new_tsv_pd['group'].str.lower()
new_tsv_pd.replace({np.nan: 'n/a'}, inplace=True)

In [127]:
new_tsv_pd.columns

Index(['participant_id', 'sex', 'group', 'age', 'toni_index',
       'ctopp_phon_awareness', 'celf_core_language', 'celf_receptive_language',
       'celf_expressive_language', 'pta', 'win_correct_avg', 'win_score_avg'],
      dtype='object')

In [128]:
new_tsv_pd.dtypes

participant_id               object
sex                          object
group                        object
age                         float64
toni_index                   object
ctopp_phon_awareness         object
celf_core_language           object
celf_receptive_language      object
celf_expressive_language     object
pta                          object
win_correct_avg              object
win_score_avg                object
dtype: object

In [129]:
new_tsv_pd

,participant_id,sex,group,age,toni_index,ctopp_phon_awareness,celf_core_language,celf_receptive_language,celf_expressive_language,pta,win_correct_avg,win_score_avg
0,sub-SSP001,F,control,11.164384,89.0,75,96.0,93.0,106.0,n/a,n/a,n/a
1,sub-SSP002,F,control,13.013699,104.0,100,114.0,100.0,112.0,n/a,n/a,n/a
2,sub-SSP005,F,control,10.490411,100.0,96,108.0,98.0,112.0,n/a,n/a,n/a
3,sub-SSP008,M,control,8.550685,104.0,98,113.0,117.0,120.0,n/a,n/a,n/a
4,sub-SSP009,M,control,9.879452,101.0,98,111.0,89.0,116.0,n/a,n/a,n/a
5,sub-SSP011,M,control,11.495890,114.0,84,117.0,105.0,122.0,n/a,n/a,n/a
6,sub-SSP012,M,control,12.989041,111.0,94,100.0,102.0,98.0,n/a,n/a,n/a
7,sub-SSP013,M,control,11.027397,99.0,71,85.0,77.0,89.0,n/a,n/a,n/a
8,sub-SSP014,F,control,11.528767,120.0,114,116.0,111.0,114.0,n/a,n/a,n/a
9,sub-SSP015,M,control,9.690411,100.0,100,96.0,107.0,98.0,n/a,n/a,n/a
10,sub-SSP017,M,control,11.219178,115.0,96,117.0,113.0,118.0,n/a,n/a,n/a
11,sub-SSP018,F,cws,8.969863,102.0,103,102.0,94.0,106.0,n/a,n/a,n/a
12,sub-SSP020,F,cws,13.238356,98.0,110,133.0,122.0,135.0,n/a,n/a,n/a
13,sub-SSP021,M,cws,8.367123,115.0,129,133.0,129.0,134.0,n/a,n/a,n/a
14,sub-SSP028,M,control,10.819178,107.0,116,100.0,102.0,100.0,n/a,26.5,4.8
15,sub-SSP032,M,control,12.956164,114.0,110,105.0,107.0,104.0,n/a,27.0,4.4
16,sub-SSP033,F,control,7.767123,99.0,92,107.0,121.0,106.0,n/a,25.5,5.6
17,sub-SSP034,F,control,9.279452,106.0,103,123.0,104.0,122.0,n/a,24.5,6.4
18,sub-SSP036,M,control,11.624658,128.0,114,140.0,135.0,133.0,0.625,25.5,5.6
19,sub-SSP038,M,control,9.926027,100.0,75,101.0,103.0,93.0,7.5,25.0,6.0
20,sub-SSP039,M,control,12.939726,88.0,98,105.0,109.0,104.0,7.5,27.0,4.4
21,sub-SSP040,F,control,9.024658,139.0,100,123.0,123.0,126.0,14.375,28.0,3.6
22,sub-SSP041,M,control,11.575342,125.0,90,107.0,113.0,104.0,3.125,25.5,5.6
23,sub-SSP045,M,cws,10.734247,106.0,80,117.0,117.0,110.0,5.625,27.0,4.4
24,sub-SSP046,M,cws,9.536986,104.0,112,125.0,131.0,124.0,5.0,26.0,5.2
25,sub-SSP048,M,cws,8.983562,107.0,96,111.0,135.0,108.0,3.75,26.0,5.2
26,sub-SSP051,F,control,8.142466,106.0,84,118.0,115.0,116.0,9.375,27.0,4.4
27,sub-SSP054,F,control,11.745205,108.0,112,127.0,125.0,124.0,6.875,27.0,4.4
28,sub-SSP056,F,control,8.249315,105.0,114,120.0,111.0,116.0,11.875,25.0,6.0
29,sub-SSP058,F,cws,7.728767,110.0,90,95.0,85.0,98.0,11.25,24.5,6.4
30,sub-SSP060,M,control,8.202740,96.0,135,113.0,102.0,116.0,3.125,26.0,5.2
31,sub-SSP062,M,control,8.079452,80.0,82,111.0,89.0,118.0,9.375,24.5,6.4
32,sub-SSP064,M,cws,11.791781,97.0,84,94.0,102.0,93.0,10.625,26.0,5.2
33,sub-SSP074,M,control,9.923288,99.0,105,120.0,120.0,116.0,5.0,25.5,5.6
34,sub-SSP076,F,control,11.498630,97.0,84,113.0,113.0,106.0,1.875,25.5,5.6
35,sub-SSP077,M,control,8.567123,87.0,92,85.0,85.0,87.0,-0.625,23.0,7.6
36,sub-SSP078,M,cws,10.901370,88.0,82,103.0,91.0,114.0,3.125,25.0,6.0
37,sub-SSP081,M,cws,7.745205,104.0,105,104.0,109.0,108.0,1.25,23.0,7.6
38,sub-SSP083,F,control,8.641096,121.0,100,109.0,117.0,118.0,0.625,25.5,5.6
39,sub-SSP084,M,control,11.205479,111.0,100,100.0,93.0,106.0,1.25,25.0,6.0
40,sub-SSP085,F,control,7.553425,109.0,127,120.0,121.0,116.0,3.75,23.5,7.2
41,sub-SSP086,F,control,7.723288,100.0,103,107.0,107.0,112.0,7.5,24.5,6.4
42,sub-SSP089,M,cws,8.695890,96.0,107,105.0,102.0,110.0,6.875,21.0,9.2
43,sub-SSP090,M,cws,8.380822,106.0,112,109.0,100.0,114.0,5.625,25.0,6.0
44,sub-SSP091,M,control,11.038356,104.0,98,113.0,105.0,108.0,1.25,25.5,5.6
45,sub-SSP092,F,control,9.887671,114.0,98,105.0,102.0,108.0,0.625,24.0,6.8
46,sub-SSP093,M,cws,9.049315,100.0,88,98.0,92.0,100.0,2.5,25.5,5.6
47,sub-SSP094,M,cws,9.846575,100.0,94,96.0,86.0,110.0,10.625,26.0,5.2
48,sub-SSP095,F,control,11.126027,114.0,122,127.0,127.0,126.0,4.375,26.5,4.8
49,sub-SSP097,F,control,8.479452,98.0,110,98.0,94.0,106.0,5.625,24.0,6.8
50,sub-SSP099,F,control,12.002740,107.0,94,126.0,131.0,120.0,-7.5,26.0,5.2
51,sub-SSP100,M,control,7.684932,105.0,122,111.0,109.0,114.0,1.875,24.5,6.4
52,sub-SSP102,F,control,8.569863,96.0,96,85.0,85.0,89.0,3.75,24.0,6.8
53,sub-SSP103,M,control,10.994521,103.0,98,102.0,103.0,106.0,3.75,24.0,6.8
54,sub-SSP106,M,control,9.301370,n/a,n/a,n/a,n/a,n/a,n/a,n/a,n/a
55,sub-SSP107,M,control,11.301370,n/a,n/a,n/a,n/a,n/a,n/a,n/a,n/a

## Overwrite existing `participants.tsv` file

In [132]:
new_tsv_pd.to_csv(
    tsv_fpath,
    sep='\t',
    index=False,
    na_rep='n/a'
)

# Write new `participants.json`

In [130]:
participants_json = {
    "participant_id": {
        "Description": "Unique participant identifier"
    },
    "age": {
        "Description": "Age at time of MRI",
        "Units": "years"
    },
    "sex": {
        "Description": "Biological sex",
        "Levels": {"F": "female", "M": "male"}
    },
    "group": {
        "Description": "Experimental group"
    },
    "toni_index": {
        "Description": "Test of Nonverbal Intelligence, Index score"
    },
    "ctopp_phon_awareness": {
        "Description": "CTOPP phonological awareness standard score"
    },
    "celf_core_language": {
        "Description": "CELF core language standard score"
    },
    "celf_receptive_language": {
        "Description": "CELF receptive language standard score"
    },
    "celf_expressive_language": {
        "Description": "CELF expressive language standard score"
    },
    "pta": {
        "Description": "Pure tone average hearing threshold",
        "Units": "dB HL"
    }
}

In [131]:
import json
json_fpath = os.path.join(bids_dir, 'participants.json')
with open(json_fpath, 'w') as f:
    json.dump(participants_json, f, indent=2)